"""PRD-165: Strategy Selector.

Revision ID: 165
Revises: 163
Create Date: 2025-02-09
"""

from alembic import op
import sqlalchemy as sa

revision = "165"
down_revision = "163"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Strategy selections: records of which strategy was chosen per ticker
    op.create_table(
        "strategy_selections",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("selection_id", sa.String(50), unique=True, index=True, nullable=False),
        sa.Column("ticker", sa.String(20), nullable=False, index=True),
        sa.Column("selected_strategy", sa.String(30), nullable=False, index=True),
        sa.Column("trend_strength", sa.String(20)),
        sa.Column("adx_value", sa.Float),
        sa.Column("regime", sa.String(20)),
        sa.Column("confidence", sa.Float),
        sa.Column("reasoning", sa.Text),
        sa.Column("selected_at", sa.DateTime(timezone=True), index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Mean reversion signals: generated by the mean-reversion strategy path
    op.create_table(
        "mean_reversion_signals",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("signal_id", sa.String(50), unique=True, index=True, nullable=False),
        sa.Column("ticker", sa.String(20), nullable=False, index=True),
        sa.Column("direction", sa.String(10), nullable=False, index=True),
        sa.Column("conviction", sa.Float),
        sa.Column("rsi", sa.Float),
        sa.Column("zscore", sa.Float),
        sa.Column("bb_position", sa.Float),
        sa.Column("entry_price", sa.Float),
        sa.Column("target_price", sa.Float),
        sa.Column("stop_price", sa.Float),
        sa.Column("signal_type", sa.String(30), nullable=False, index=True),
        sa.Column("signal_time", sa.DateTime(timezone=True), index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("mean_reversion_signals")
    op.drop_table("strategy_selections")
