"""Email notification channel.

SMTP-based email delivery with HTML formatting.
"""

import logging
import re
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from src.alerts.channels.base import DeliveryChannel
from src.alerts.config import EmailConfig
from src.alerts.models import Notification

logger = logging.getLogger(__name__)

EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")


class EmailChannel(DeliveryChannel):
    """Email delivery channel via SMTP."""

    def __init__(self, config: Optional[EmailConfig] = None) -> None:
        self.config = config or EmailConfig()
        self._delivery_log: list[dict] = []

    def send(self, notification: Notification) -> bool:
        """Send email notification.

        Args:
            notification: Notification with recipient email.

        Returns:
            True if sent successfully.
        """
        if not self.validate_recipient(notification.recipient):
            notification.mark_failed("Invalid email address")
            return False

        if not self.config.sender_email:
            # No SMTP configured — log and mark as sent (dry run)
            self._delivery_log.append({
                "to": notification.recipient,
                "subject": notification.subject or "Axion Alert",
                "body": notification.message,
                "status": "dry_run",
            })
            notification.mark_sent()
            logger.info(
                "Email (dry run) to %s: %s",
                notification.recipient, notification.subject,
            )
            return True

        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = f"{self.config.sender_name} <{self.config.sender_email}>"
            msg["To"] = notification.recipient
            msg["Subject"] = notification.subject or "Axion Alert"

            # Plain text
            msg.attach(MIMEText(notification.message, "plain"))

            # HTML version
            html = self._format_html(notification)
            msg.attach(MIMEText(html, "html"))

            with smtplib.SMTP(self.config.smtp_host, self.config.smtp_port) as server:
                if self.config.use_tls:
                    server.starttls()
                if self.config.username:
                    server.login(self.config.username, self.config.password)
                server.send_message(msg)

            notification.mark_sent()
            self._delivery_log.append({
                "to": notification.recipient,
                "subject": msg["Subject"],
                "status": "sent",
            })
            return True

        except Exception as e:
            notification.mark_failed(str(e))
            logger.error("Email delivery failed: %s", e)
            return False

    def validate_recipient(self, recipient: str) -> bool:
        """Validate email address format."""
        return bool(EMAIL_REGEX.match(recipient))

    def get_delivery_log(self) -> list[dict]:
        """Get delivery log for debugging."""
        return list(self._delivery_log)

    def _format_html(self, notification: Notification) -> str:
        """Format notification as HTML email."""
        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #1a1a2e; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
                <h2 style="margin: 0;">Axion Alert</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
                <p style="font-size: 16px; color: #333;">{notification.message}</p>
                <hr style="border: none; border-top: 1px solid #e0e0e0;">
                <p style="font-size: 12px; color: #999;">
                    This alert was generated by the Axion platform.
                </p>
            </div>
        </body>
        </html>
        """
